version: '3.8'

services:
  llm-server:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: local-llm-server
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/model.gguf
      - LOG_LEVEL=INFO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    networks:
      - llm-network
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G

networks:
  llm-network:
    driver: bridge