version: "3.9"

services:
  ollama-offline-agent:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - models:/root/.ollama
    environment:
      - OLLAMA_MODEL=llama3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  models:
