services:
  llm-server-gpu:
    build:
      context: .
      dockerfile: docker/Dockerfile.gpu
    container_name: local-llm-server-gpu
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models:ro
      - ./config:/app/config:ro
      - ./logs:/app/logs
    environment:
      - PYTHONUNBUFFERED=1
      - MODEL_PATH=/app/models/model.gguf
      - LOG_LEVEL=INFO
      - CUDA_VISIBLE_DEVICES=0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
          memory: 6G
    networks:
      - llm-network

networks:
  llm-network:
    driver: bridge